### ISSUE TITLE
locktime = 0 

### ISSUE THREAD

**Issue by aryeharmon** [greenaddress/garecovery#12]
What do i do if the transation ID does not show up in the blockchain and the lock time value is 0?

**Comment by jkauffman1** [comment]
Hi,
Please could you clarify whether you mean that the utxo transaction is not visible, or that the recovery transaction is not visible? Note that the tool will not automatically broadcast the recovery transaction, that is left to the user.

**Comment by aryeharmon** [comment]
Recovery, how do I broadcast the transaction?

**Comment by jkauffman1** [comment]
If you look at the README it describes this step at the end of the section on 2of2 recovery

https://github.com/greenaddress/garecovery#2of2-recovery

**Comment by aryeharmon** [comment]
I am getting invalid transaction I'd when I broadcast

**Comment by jkauffman1** [comment]
Please email GreenAddress support for further assistance
info@greenaddress.it
