### ISSUE TITLE
Non-canonical DER signature

### ISSUE THREAD

**Issue by the9ull** [greenaddress/garecovery#13]
I spent BCH from 2 wallets without problems. The third one generates transactions that are not accepted by BCH network for not-canonical DER signature

**Comment by greenaddress** [comment]
Hi,

We don't support forks of our software such as the one used in the issue being reported however we believe this issue may affect upstream too (i.e. our vanilla garecovery tool)

Can you send a copy of the affected transaction to our support at info@greenaddress.it with a link to this github issue?
