### ISSUE TITLE
Does the 2of2 method work for getting BCH?

### ISSUE THREAD

**Issue by czzarr** [greenaddress/garecovery#2]

**Comment by jgriffiths** [comment]
Hi,

Neither 2of2 or 2of3 recovery transactions are valid on the bcash chain since it implements 2 way replay protection using a modified segwit scheme to sign its transactions.

**Comment by shorena** [comment]
Is there any plan to allow users a recovery path for their BCH? Not sure how many users of your wallet a long term hodlers, but they likely have missed the announcement. I understand why you dont want to disclose the private keys for 2-2, but maybe sign BCH TX as well as BTC TX.
