### ISSUE TITLE
Coin recovery

### ISSUE THREAD

**Issue by LionCurrency** [greenaddress/garecovery#22]
Dear developers! Can anyone describe the full procedure for the recovery of coins? I'm not a programmer, and I do not know Python. I can not do anything according to the instructions given here. Can anyone write more details?

**Comment by greenaddress** [comment]
Hello, sorry for the late reply, we missed a notification somewhere.

The guide is currently on the README here https://github.com/greenaddress/garecovery and while it doesn't require a developer it does require someone with console/shell/command line experience.

We'll update the README and the tool also comes with a help file however it still requires someone with command line experience. In the future we plan to integrate this functionality in the wallets to simplify usage.

thanks

**Comment by Xyu201099** [comment]
В итоге, как можно восстановить монеты????
