### ISSUE TITLE
Exporting Private Key

### ISSUE THREAD

**Issue by gaia** [greenaddress/garecovery#27]
I have the mnemonic of a simple wallet (not 2of2 or 2of3) and would like to export the private key,

What is the syntax for this?

Thank you

**Comment by yummie08** [comment]
help me to recover

**Comment by Apichat11oat** [comment]
Yes i want to export private key

**Comment by jgriffiths** [comment]
Hi, please address support questions to info@greenaddress.it in the future.

Green only supports 2of2 and 2of3 wallets, it does not currently support single signature (e.g. bip 44) style wallets - single sig support is being worked on now. So you can't export a private key and expect it to import it into another wallet.

If you have the mnemonic then you can install another instance of the wallet (desktop, mobile etc), enter the mnemonic into it, and your coins should be available to you.
