### ISSUE TITLE
wallet recovery

### ISSUE THREAD

**Issue by doctorberg** [greenaddress/garecovery#48]
I forgot my wallet password, 2fa electrorum, I have a seed and 2fa, I restored the wallet, but the balance is empty, the wallet balance is positive on the blockchain, there is a wallet address, hash 3 transactions..
found this information:
If you are sure that the seed is correct, but the balances are still empty, all that remains is to try to find the address and extract the private key by changing the derivation paths.
There is an ElectrumSeedTester tool on GitHub.

Then I downloaded the ElectrumSeedTester. and in the field "BIP39 Mnemonic" I inserted my seed..

after nothing happened, I didn't see the private keys..
To test this method, I created a standard wallet with a new seed, using the new wallet seed in the BIP39 field, I found that this method worked, the private keys were visible..
then I created a new 2fa wallet, what do you think?
seed 2 fa wallet did not display private keys...
what should I do please tell me, thank you for your attention..

**Comment by doctorberg** [comment]
> Я забыл пароль своего кошелька, 2fa electrorum, у меня есть сид и 2fa, я восстановил кошелек, но баланс пуст, баланс кошелька положительный на блокчейне, есть адрес кошелька, хэш 3 транзакции. Нашел эту информацию: Если вы уверены, что синик правильный, но балансы все еще пусты, все, что остается, это попытаться найти адрес и извлечь закрытый ключ, изменив пути вывода. На GitHub есть инструмент ElectrumSeedTester.
> 
> Затем я скачал ElectrumSeedTester. и в поле "BIP39 Мнемоника" я вставил свое семя..
> 
> после того, как ничего не произошло, я не увидел закрытых ключей. Чтобы протестировать этот метод, я создал стандартный кошелек с новым семенем, используя новое семя кошелька в поле BIP39, я обнаружил, что этот метод работает, закрытые ключи были видны. затем я создал новый кошелек 2fa, что вы думаете? seed 2 fa кошелек не отображал закрытые ключи... что мне делать, пожалуйста, скажите мне, спасибо за внимание.

**Comment by jgriffiths** [comment]
Hi @doctorberg 

Please contact support via https://help.blockstream.com/hc/en-us with the above. Its a little unclear to me what your situation is exactly, but our support team should be able to clear things up for you.

Closing this issue in favour of you opening a support ticket.
