### ISSUE TITLE
Help with green wallet error code and disappearance

### ISSUE THREAD

**Issue by moxiemamasjewels** [greenaddress/garecovery#50]
I need some help with green wallet I am semi amateur to all this and learn as I go I put it today and it was working fine for sending and receiving Bitcoin and then stopped working and I got it lots of different numbers coming up and then it stopped sending and now it has disappeared
I would love some help and guidance it at any point .

**Comment by jgriffiths** [comment]
Hi @moxiemamasjewels,

please contact our support team as described at https://help.blockstream.com/ and they can take you through any issues you are having.
