### ISSUE TITLE
Error while running readme commands

### ISSUE THREAD

**Issue by secondl1ght** [greenaddress/garecovery#51]
While trying to install the tool via the README commands, I made it to the `pip install --require-hashes -r tools/requirements.txt` command and received the following output in the terminal: `ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'tools/requirements.txt'`.

Is there a reason why this directory doesn't exist for me when following the steps?

**Comment by jgriffiths** [comment]
The file is in the repo: https://github.com/greenaddress/garecovery/blob/master/tools/requirements.txt

make sure you are in the root directory of the repo when running the install commands.

**Comment by secondl1ght** [comment]
Thanks I wasn't sure if I needed to git clone the repo or not.
